# Attempt to load a config.make file.
# If none is found, project defaults in config.project.make will be used.
-include config.make

# make sure the the OF_ROOT location is defined
OF_ROOT ?= ../../..


# call the project makefile!
include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
